In [1]:
import sys
!{sys.executable} -m pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\karwi\appdata\local\programs\python\python313\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\karwi\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.4.3)
Requirement already satisfied: scipy>=1.10.0 in c:\users\karwi\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\karwi\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\karwi\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 24.3.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import matplotlib as pt
import sklearn

In [3]:
master_sheet = pd.read_csv("PAM ML Master Sheet - Hoja 1.csv")

In [4]:
master_sheet.head()

,Friction Reducer,Form,Charge Density (%),TDS,Boron (B),Barium (Ba+2),Calcium (Ca+2),Iron (Fe+2),Potassium (K+),Magnesium (Mg+2),...,300,250,200,150,100,50,25,"12,5",0,R^2
0,A,ePAM,32,"5876,0","6,0","0,3","385,5",0,"54,9","89,1",...,"1,725","1,470","1,328","0,899","0,595","0,293","0,139","0,050","0,000","0,978"
1,A,ePAM,32,164384,"25,7","4,4","8908,0","0,0","1082,0","940,4",...,"1,790","1,530","1,470","1,004","0,660","0,334","0,151","0,065","0,000","0,954"
2,A,ePAM,32,89081,"18,1","4,7","5255,0",0,"469,8","549,3",...,"1,802","1,514","1,414","0,952","0,644","0,323","0,169","0,077","0,000","0,9628"

In [5]:
master_sheet.dtypes

Friction Reducer            str
Form                        str
Charge Density (%)        int64
TDS                         str
Boron (B)                   str
Barium (Ba+2)               str
Calcium (Ca+2)              str
Iron (Fe+2)                 str
Potassium (K+)              str
Magnesium (Mg+2)            str
Manganese (Mn+2)            str
Sodium (Na+)            float64
Strontium (Sr+2)            str
Zinc (Zn+2)                 str
Fluoride (F⁻)             int64
Chlorides (Cl-)         float64
Nitrite (NO₂⁻)            int64
Bromide (Br⁻)               str
Nitrate (NO₃⁻)            int64
Phosphate (PO₄³⁻)         int64
Sulfate (SO4-2)             str
Bicarbonates (HCO3-)      int64
500                         str
300                         str
250                         str
200                         str
150                         str
100                         str
50                          str
25                          str
12,5                        str
0                           str
R^2                         str
dtype: object

In [6]:
numeric_cols =['TDS','Boron (B)', 'Barium (Ba+2)',	'Calcium (Ca+2)','Iron (Fe+2)','Potassium (K+)','Magnesium (Mg+2)','Manganese (Mn+2)','Strontium (Sr+2)','Zinc (Zn+2)', 'Bromide (Br⁻)', '500','300',	'250', '200',	'150',	'100',	'50',	'25',	'12,5',	'0', 'R^2']
for col in numeric_cols:
    master_sheet[col] = master_sheet[col].str.replace(',','.')

In [7]:
numeric_cols = ['Charge Density (%)',
                'TDS','Boron (B)', 'Barium (Ba+2)',	'Calcium (Ca+2)','Iron (Fe+2)','Potassium (K+)','Magnesium (Mg+2)','Manganese (Mn+2)','Sodium (Na+)','Strontium (Sr+2)','Zinc (Zn+2)','Fluoride (F⁻)', 'Chlorides (Cl-)', 'Nitrite (NO₂⁻)', 'Bromide (Br⁻)', 'Nitrate (NO₃⁻)', 'Phosphate (PO₄³⁻)', 'Sulfate (SO4-2)', 'Bicarbonates (HCO3-)', '500','300',	'250', '200',	'150',	'100',	'50',	'25',	'12,5',	'0', 'R^2']
for col in numeric_cols:
    master_sheet[col] = pd.to_numeric(master_sheet[col], errors='coerce')

In [8]:
master_sheet.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 33 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Friction Reducer      3 non-null      str
 1   Form                  3 non-null      str
 2   Charge Density (%)    3 non-null      int64
 3   TDS                   3 non-null      float64
 4   Boron (B)             3 non-null      float64
 5   Barium (Ba+2)         3 non-null      float64
 6   Calcium (Ca+2)        3 non-null      float64
 7   Iron (Fe+2)           3 non-null      float64
 8   Potassium (K+)        3 non-null      float64
 9   Magnesium (Mg+2)      3 non-null      float64
 10  Manganese (Mn+2)      3 non-null      float64
 11  Sodium (Na+)          3 non-null      float64
 12  Strontium (Sr+2)      3 non-null      float64
 13  Zinc (Zn+2)           3 non-null      float64
 14  Fluoride (F⁻)         3 non-null      int64
 15  Chlorides (Cl-)       3 non-null      float64
 16  Nitrite (NO₂⁻)        3 non-null      int64
 17  Bromide (Br⁻)         3 non-null      float64
 18  Nitrate (NO₃⁻)        3 non-null      int64
 19  Phosphate (PO₄³⁻)     3 non-null      int64
 20  Sulfate (SO4-2)       0 non-null      float64
 21  Bicarbonates (HCO3-)  3 non-null      int64
 22  500                   3 non-null      float64
 23  300                   3 non-null      float64
 24  250                   3 non-null      float64
 25  200                   3 non-null      float64
 26  150                   3 non-null      float64
 27  100                   3 non-null      float64
 28  50                    3 non-null      float64
 29  25                    3 non-null      float64
 30  12,5                  3 non-null      float64
 31  0                     3 non-null      float64
 32  R^2                   3 non-null      float64
dtypes: float64(25), int64(6), str(2)
memory usage: 924.0 bytes

In [9]:
master_sheet.head()

,Friction Reducer,Form,Charge Density (%),TDS,Boron (B),Barium (Ba+2),Calcium (Ca+2),Iron (Fe+2),Potassium (K+),Magnesium (Mg+2),...,300,250,200,150,100,50,25,"12,5",0,R^2
0,A,ePAM,32,5876.0,6.0,0.3,385.5,0.0,54.9,89.1,...,1.725,1.470,1.328,0.899,0.595,0.293,0.139,0.050,0.0,0.9780
1,A,ePAM,32,164384.0,25.7,4.4,8908.0,0.0,1082.0,940.4,...,1.790,1.530,1.470,1.004,0.660,0.334,0.151,0.065,0.0,0.9540
2,A,ePAM,32,89081.0,18.1,4.7,5255.0,0.0,469.8,549.3,...,1.802,1.514,1.414,0.952,0.644,0.323,0.169,0.077,0.0,0.9628

In [10]:
master_sheet.notna().value_counts()

Friction Reducer  Form  Charge Density (%)  TDS   Boron (B)  Barium (Ba+2)  Calcium (Ca+2)  Iron (Fe+2)  Potassium (K+)  Magnesium (Mg+2)  Manganese (Mn+2)  Sodium (Na+)  Strontium (Sr+2)  Zinc (Zn+2)  Fluoride (F⁻)  Chlorides (Cl-)  Nitrite (NO₂⁻)  Bromide (Br⁻)  Nitrate (NO₃⁻)  Phosphate (PO₄³⁻)  Sulfate (SO4-2)  Bicarbonates (HCO3-)  500   300   250   200   150   100   50    25    12,5  0     R^2
True              True  True                True  True       True           True            True         True            True              True              True          True              True         True           True             True            True           True            True               False            True                  True  True  True  True  True  True  True  True  True  True  True    3
Name: count, dtype: int64